### ISSUE TITLE
No way to contact payetools

### ISSUE THREAD

**Issue by will-0** [payetools/Payetools#89]
Readme specifies "if you are interested in joining the project, please contact payetools via Github". Unfortunately, there is no contact information available on that GitHub account!

Am interested in the work you are doing here. Would be grateful to indicate how to get involved.

**Comment by payetools** [comment]
Will - sorry it's been 3 weeks since you raised your issue - Payetools doesn't have my full-time attention but that is no excuse.  You can reach me at dev [at] payetools.com - please drop me a line there with a little more background to your interest.  There is a fair amount of churn in the repo at the moment, so managing external contributions needs a little care.

Many thanks - Steve.

**Comment by will-0** [comment]
Many thanks! Have dropped you an email.
